In [2]:
import numpy as np

## 1. DataTypes & Attributes

In [3]:
# Numpy's main datatype is ndarray (n-dimentional array)

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10, 11,12],
                [13,14,15],
                [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [16]:
sample_array = np.array ( [1,2,3])
sample_array

array([1, 2, 3])

In [17]:
ones = np.ones((2,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10,size = (3,5))
random_array

array([[8, 7, 5, 5, 8],
       [3, 3, 9, 3, 5],
       [6, 4, 3, 5, 4]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.0075899 , 0.57635145, 0.28391601],
       [0.48054785, 0.18288991, 0.82194808],
       [0.32268391, 0.94141082, 0.40096112],
       [0.57266027, 0.29823824, 0.43529596],
       [0.17286207, 0.3729812 , 0.46345788]])

In [27]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.23095377, 0.44095762, 0.22982951],
       [0.55123944, 0.81980589, 0.55047056],
       [0.59670335, 0.91992885, 0.73922037],
       [0.89661382, 0.76170134, 0.54815941],
       [0.00635004, 0.21058064, 0.78395849]])

In [28]:
# pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size = (5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrices

In [29]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a3.shape

(2, 3, 3)

In [31]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [33]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [34]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [35]:
a4[1, 2, 0]

array([2, 3, 4, 1, 2])

In [36]:
a4[:, :, :, :2]

array([[[[6, 7],
         [5, 9],
         [3, 0],
         [2, 3]],

        [[3, 3],
         [9, 9],
         [3, 2],
         [0, 4]],

        [[8, 4],
         [8, 1],
         [9, 3],
         [0, 3]]],


       [[[4, 6],
         [4, 4],
         [7, 5],
         [5, 9]],

        [[0, 1],
         [0, 3],
         [5, 9],
         [2, 9]],

        [[2, 3],
         [9, 1],
         [2, 3],
         [0, 6]]]])

## 4. Manipulating & Comparing arrays

### Atrithmetic

In [37]:
a1

array([1, 2, 3])

In [38]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [39]:
a1 + ones

array([2., 3., 4.])

In [40]:
a1 - ones

array([0., 1., 2.])

In [41]:
a1 * ones

array([1., 2., 3.])

In [42]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [43]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [45]:
a1 / ones

array([1., 2., 3.])

In [46]:
a1 // ones

array([1., 2., 3.])

In [47]:
# Floor division removes the decimals 
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [48]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [49]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [50]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [51]:
np.add(a1, ones)

array([2., 3., 4.])

In [52]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [53]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [54]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [55]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [56]:
listy_list = [1,2,3]
type(listy_list)

list

In [57]:
sum(listy_list)

6

In [58]:
sum(a1)

6

In [59]:
np.sum(a1)

6

Use python's methods (`sum()`) on python datatypes and use NumPy's methods on NumPy's arrays (`np.sum()`).

In [60]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [61]:
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [62]:
%timeit sum(massive_array) # Py7thon's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

6.89 ms ± 770 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
41.4 µs ± 6.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [63]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [64]:
np.mean(a2)

3.6333333333333333

In [65]:
np.max(a2)

6.5

In [66]:
np.min(a2)

1.0

In [67]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [68]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [69]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

In [70]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [71]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [72]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [73]:
np.mean(high_var_array), np.mean(low_var_array)

(1600.1666666666667, 6.0)

In [74]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

In [75]:
plt.hist(low_var_array)
plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

### Reshaping & transposing

In [76]:
a2.shape

(2, 3)

In [77]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [78]:
a3.shape

(2, 3, 3)

In [82]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [83]:
a2_reshape = a2.reshape(2,3,1)

In [84]:
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [85]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [87]:
a2.shape

(2, 3)

In [88]:
# Transpose = switches the axis
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [89]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
a3.shape

(2, 3, 3)

In [92]:
a3.T.shape

(3, 3, 2)

In [94]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])