In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray (n-dimentional array)

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10, 11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array ( [1,2,3])
sample_array

array([1, 2, 3])

In [16]:
ones = np.ones((2,3))

In [17]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10,size = (3,5))
random_array

array([[5, 6, 2, 2, 3],
       [1, 0, 9, 6, 0],
       [5, 0, 2, 3, 0]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.18853989, 0.4863251 , 0.32871901],
       [0.15775943, 0.43398627, 0.68830234],
       [0.77008208, 0.43634799, 0.28252939],
       [0.57132405, 0.27340728, 0.29260368],
       [0.42675204, 0.25482734, 0.3998247 ]])

In [26]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.42597028, 0.43634514, 0.56715196],
       [0.76749266, 0.19781019, 0.14511731],
       [0.91612855, 0.04486371, 0.04877594],
       [0.01055992, 0.79707436, 0.51701806],
       [0.48752575, 0.41709539, 0.32989768]])

In [27]:
# pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size = (5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrices

In [28]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a3.shape

(2, 3, 3)

In [30]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [32]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [33]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [38]:
a4[1, 2, 0]

array([2, 3, 4, 1, 2])

In [40]:
a4[:, :, :, :2]

array([[[[6, 7],
         [5, 9],
         [3, 0],
         [2, 3]],

        [[3, 3],
         [9, 9],
         [3, 2],
         [0, 4]],

        [[8, 4],
         [8, 1],
         [9, 3],
         [0, 3]]],


       [[[4, 6],
         [4, 4],
         [7, 5],
         [5, 9]],

        [[0, 1],
         [0, 3],
         [5, 9],
         [2, 9]],

        [[2, 3],
         [9, 1],
         [2, 3],
         [0, 6]]]])

## 4. Manipulating & Comparing arrays

### Atrithmetic

In [41]:
a1

array([1, 2, 3])

In [44]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [45]:
a1 + ones

array([2., 3., 4.])

In [46]:
a1 - ones

array([0., 1., 2.])

In [47]:
a1 * ones

array([1., 2., 3.])

In [48]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [49]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a1 / ones

array([1., 2., 3.])

In [52]:
a1 // ones

array([1., 2., 3.])

In [55]:
# Floor division removes the decimals 
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [56]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [57]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [58]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [59]:
np.add(a1, ones)

array([2., 3., 4.])

In [60]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [61]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [62]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [63]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [64]:
listy_list = [1,2,3]
type(listy_list)

list

In [65]:
sum(listy_list)

6

In [66]:
sum(a1)

6

In [67]:
np.sum(a1)

6

Use python's methods (`sum()`) on python datatypes and use NumPy's methods on NumPy's arrays (`np.sum()`).

In [68]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [70]:
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [71]:
%timeit sum(massive_array) # Py7thon's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

6.47 ms ± 224 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
38.1 µs ± 1.84 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [72]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [74]:
np.mean(a2)

3.6333333333333333

In [75]:
np.max(a2)

6.5

In [76]:
np.min(a2)

1.0

In [78]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [79]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [80]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422