In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray (n-dimentional array)

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10, 11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [17]:
sample_array = np.array ( [1,2,3])
sample_array

array([1, 2, 3])

In [18]:
ones = np.ones((2,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10,size = (3,5))
random_array

array([[8, 3, 6, 1, 4],
       [1, 5, 2, 5, 6],
       [2, 4, 2, 5, 6]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [32]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.03024522, 0.3523881 , 0.05808061],
       [0.40714819, 0.96554362, 0.54840062],
       [0.97025672, 0.08329331, 0.47053093],
       [0.96619059, 0.66239138, 0.92146731],
       [0.20084221, 0.23947579, 0.2127887 ]])

In [33]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.45309595, 0.80996236, 0.13820039],
       [0.35344458, 0.24839652, 0.78864772],
       [0.19465161, 0.42874999, 0.05850378],
       [0.65462035, 0.70148824, 0.0277779 ],
       [0.15074804, 0.57070732, 0.13195746]])