In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray (n-dimentional array)

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10, 11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array ( [1,2,3])
sample_array

array([1, 2, 3])

In [16]:
ones = np.ones((2,3))

In [17]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10,size = (3,5))
random_array

array([[6, 2, 8, 0, 8],
       [6, 4, 0, 2, 7],
       [0, 6, 2, 6, 8]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.5002672 , 0.13143397, 0.33299775],
       [0.41694054, 0.01817959, 0.3996041 ],
       [0.3561687 , 0.45377656, 0.10845124],
       [0.40087995, 0.65390479, 0.34202248],
       [0.8302092 , 0.16091202, 0.64067642]])

In [26]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.49362169, 0.73920952, 0.62552744],
       [0.40733998, 0.09964806, 0.99720842],
       [0.72953346, 0.00206521, 0.52838584],
       [0.22400236, 0.92625791, 0.71688658],
       [0.48326952, 0.89890567, 0.848922  ]])

In [36]:
# pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size = (5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])